Data Cleaning & Preparation

In [4]:
import pandas as pd

In [25]:
# Merging the two dataframes

df1 = pd.read_csv('../Churn_Model/data/orders.csv')
df2 = pd.read_csv('../Churn_Model/data/return.csv')

# Merge the DataFrames (adjust 'on' parameter as needed)
df = pd.merge(df1, df2, on='Order ID')

# Display the merged DataFrame
df.head()

,Row ID,Order ID,Order Date,Ship Date,Delivery Duration,Ship Mode,Customer ID,Customer Name,Segment,Country,...,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Discount Value,Profit,COGS,Returned
0,19,CA-2014-143336,8/27/14,9/1/14,5,Second Class,ZD-21925,Zuschuss Donatelli,Consumer,United States,...,Office Supplies,Art,Newell 341,8.56,2,0.0,0.000,2.4824,-6.0776,Yes
1,20,CA-2014-143336,8/27/14,9/1/14,5,Second Class,ZD-21925,Zuschuss Donatelli,Consumer,United States,...,Technology,Phones,Cisco SPA 501G IP Phone,213.48,3,0.2,-42.696,16.0110,-154.7730,Yes
2,21,CA-2014-143336,8/27/14,9/1/14,5,Second Class,ZD-21925,Zuschuss Donatelli,Consumer,United States,...,Office Supplies,Binders,"Wilson Jones Hanging View Binder, White, 1""",22.72,4,0.2,-4.544,7.3840,-10.7920,Yes
3,56,CA-2016-111682,6/17/16,6/18/16,1,First Class,TB-21055,Ted Butterfield,Consumer,United States,...,Office Supplies,Storage,Home/Office Personal File Carts,208.56,6,0.0,0.000,52.1400,-156.4200,Yes
4,57,CA-2016-111682,6/17/16,6/18/16,1,First Class,TB-21055,Ted Butterfield,Consumer,United States,...,Office Supplies,Paper,Xerox 232,32.40,5,0.0,0.000,15.5520,-16.8480,Yes

In [26]:
# Drop columns that are not needed
df.drop(columns=['Row ID', 'Customer Name', 'Product Name'], inplace=True)

In [36]:
# Change Dtype
df['Order Date'] = pd.to_datetime(df['Order Date'])
df['Ship Date'] = pd.to_datetime(df['Ship Date'])

# Make new column where returned is 1 and not returned is 0
df['Returned'] = df['Returned'].apply(lambda x: 1 if x == 'Yes' else 0)

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 800 entries, 0 to 799
Data columns (total 22 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Order ID           800 non-null    object
 1   Order Date         800 non-null    datetime64[ns]
 2   Ship Date          800 non-null    datetime64[ns]
 3   Delivery Duration  800 non-null    int64
 4   Ship Mode          800 non-null    object
 5   Customer ID        800 non-null    object
 6   Segment            800 non-null    object
 7   Country            800 non-null    object
 8   City               800 non-null    object
 9   State              800 non-null    object
 10  Postal Code        800 non-null    int64
 11  Region             800 non-null    object
 12  Product ID         800 non-null    object
 13  Category           800 non-null    object
 14  Sub-Category       800 non-null    object
 15  Sales              800 non-null    float64
 16  Quantity           800 non-null    int64
 17  Discount           800 non-null    float64
 18  Discount Value     800 non-null    float64
 19  Profit             800 non-null    float64
 20  COGS               800 non-null    float64
 21  Returned           800 non-null    int64
dtypes: datetime64[ns](2), float64(5), int64(4), object(11)
memory usage: 137.6+ KB

In [34]:
# Check for missing values
missing_values = df.isnull().sum()
print("Missing values in each column:")
print(missing_values)

# Check for duplicate rows
duplicate_rows = df.duplicated().sum()
print(f"Number of duplicate rows: {duplicate_rows}")

Missing values in each column:
Order ID             0
Order Date           0
Ship Date            0
Delivery Duration    0
Ship Mode            0
Customer ID          0
Segment              0
Country              0
City                 0
State                0
Postal Code          0
Region               0
Product ID           0
Category             0
Sub-Category         0
Sales                0
Quantity             0
Discount             0
Discount Value       0
Profit               0
COGS                 0
Returned             0
dtype: int64
Number of duplicate rows: 0

In [37]:
# save the cleaned DataFrame to a new CSV file
df.to_csv('../Churn_Model/data/cleaned_orders.csv', index=False)